name: doors
description: "life door -- safe life tools"
version: "0.1.0"
publish_to: none

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  ulid:

  isar_community:
  isar_community_flutter_libs:

  scrollable_positioned_list:

  idl:
    path: "../../../doors_lib/dart"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  isar_community_generator:
  build_runner:
  icons_launcher:

flutter:
  uses-material-design: true
  generate: true

platforms:
  android:
  ios:
  windows:
  macos:
  linux:
  web:

icons_launcher:
  image_path: "assets/door.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
