name: idl
description: "A new Flutter FFI plugin project."
version: 0.0.1
# homepage:

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:
  logger:
  flat_buffers:
  uuid:
  ulid:
  ffi:

  cryptography:

dev_dependencies:
  ffigen:
  test:
  flutter_lints:
#  hooks: ^0.20.4
#  code_assets: ^0.19.9

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
